### ISSUE TITLE
GraphqlHttpHandler should set allow origin (just like NamespaceController)

### ISSUE THREAD

**Issue by bjornandre** [statisticsnorway/linked-data-store-core#11]
I found this when running the gsim-browser locally (port 3000) with the apollo client connecting to localhost at a different port (9090).

The pre-flight request (OPTIONS), which is made by the browser, is not handled correctly by the server for the graphql endpoint.

It seems like the setting http.cors.allow.origin is ignored by the GraphqlHttpHandler

**Comment by hadrienk** [comment]
Thanks you. Handling in http://jira.ssb.no/browse/LDS-149.
